package br.edu.ifms.pykota.entidades;
// Generated 24/01/2014 12:32:52 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Coefficients generated by hbm2java
 */
@Entity
@Table(name="coefficients"
    ,catalog="pykota"
    , uniqueConstraints = @UniqueConstraint(columnNames={"printerid", "label"}) 
)
public class Coefficients  implements java.io.Serializable {


     private Integer id;
     private Printers printers;
     private String label;
     private Float coefficient;

    public Coefficients() {
    }

	
    public Coefficients(Printers printers, String label) {
        this.printers = printers;
        this.label = label;
    }
    public Coefficients(Printers printers, String label, Float coefficient) {
       this.printers = printers;
       this.label = label;
       this.coefficient = coefficient;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="printerid", nullable=false)
    public Printers getPrinters() {
        return this.printers;
    }
    
    public void setPrinters(Printers printers) {
        this.printers = printers;
    }

    
    @Column(name="label", nullable=false)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @Column(name="coefficient", precision=12, scale=0)
    public Float getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }




}


