package br.edu.ifms.pykota.entidades;
// Generated 24/01/2014 12:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="pykota"
    , uniqueConstraints = @UniqueConstraint(columnNames="groupname") 
)
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String groupname;
     private String description;
     private String limitby;
     private Set<Grouppquota> grouppquotas = new HashSet<Grouppquota>(0);
     private Set<Users> userses = new HashSet<Users>(0);

    public Groups() {
    }

	
    public Groups(String groupname) {
        this.groupname = groupname;
    }
    public Groups(String groupname, String description, String limitby, Set<Grouppquota> grouppquotas, Set<Users> userses) {
       this.groupname = groupname;
       this.description = description;
       this.limitby = limitby;
       this.grouppquotas = grouppquotas;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="groupname", unique=true, nullable=false)
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="limitby", length=30)
    public String getLimitby() {
        return this.limitby;
    }
    
    public void setLimitby(String limitby) {
        this.limitby = limitby;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set<Grouppquota> getGrouppquotas() {
        return this.grouppquotas;
    }
    
    public void setGrouppquotas(Set<Grouppquota> grouppquotas) {
        this.grouppquotas = grouppquotas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="groupsmembers", catalog="pykota", joinColumns = { 
        @JoinColumn(name="groupid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="userid", nullable=false, updatable=false) })
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


