package br.edu.ifms.pykota.entidades;
// Generated 24/01/2014 12:32:52 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Grouppquota generated by hbm2java
 */
@Entity
@Table(name="grouppquota"
    ,catalog="pykota"
    , uniqueConstraints = @UniqueConstraint(columnNames={"groupid", "printerid"}) 
)
public class Grouppquota  implements java.io.Serializable {


     private Long id;
     private Groups groups;
     private Printers printers;
     private Integer softlimit;
     private Integer hardlimit;
     private Integer maxjobsize;
     private Date datelimit;

    public Grouppquota() {
    }

    public Grouppquota(Groups groups, Printers printers, Integer softlimit, Integer hardlimit, Integer maxjobsize, Date datelimit) {
       this.groups = groups;
       this.printers = printers;
       this.softlimit = softlimit;
       this.hardlimit = hardlimit;
       this.maxjobsize = maxjobsize;
       this.datelimit = datelimit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="groupid")
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="printerid")
    public Printers getPrinters() {
        return this.printers;
    }
    
    public void setPrinters(Printers printers) {
        this.printers = printers;
    }

    
    @Column(name="softlimit")
    public Integer getSoftlimit() {
        return this.softlimit;
    }
    
    public void setSoftlimit(Integer softlimit) {
        this.softlimit = softlimit;
    }

    
    @Column(name="hardlimit")
    public Integer getHardlimit() {
        return this.hardlimit;
    }
    
    public void setHardlimit(Integer hardlimit) {
        this.hardlimit = hardlimit;
    }

    
    @Column(name="maxjobsize")
    public Integer getMaxjobsize() {
        return this.maxjobsize;
    }
    
    public void setMaxjobsize(Integer maxjobsize) {
        this.maxjobsize = maxjobsize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datelimit", length=19)
    public Date getDatelimit() {
        return this.datelimit;
    }
    
    public void setDatelimit(Date datelimit) {
        this.datelimit = datelimit;
    }




}


