package br.edu.ifms.pykota.entidades;
// Generated 24/01/2014 12:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Printers generated by hbm2java
 */
@Entity
@Table(name="printers"
    ,catalog="pykota"
    , uniqueConstraints = @UniqueConstraint(columnNames="printername") 
)
public class Printers  implements java.io.Serializable {


     private Integer id;
     private String printername;
     private String description;
     private Float priceperpage;
     private Float priceperjob;
     private String passthrough;
     private Integer maxjobsize;
     private Set<Coefficients> coefficientses = new HashSet<Coefficients>(0);
     private Set<Printers> printersesForPrinterid = new HashSet<Printers>(0);
     private Set<Grouppquota> grouppquotas = new HashSet<Grouppquota>(0);
     private Set<Printers> printersesForGroupid = new HashSet<Printers>(0);
     private Set<Userpquota> userpquotas = new HashSet<Userpquota>(0);

    public Printers() {
    }

	
    public Printers(String printername) {
        this.printername = printername;
    }
    public Printers(String printername, String description, Float priceperpage, Float priceperjob, String passthrough, Integer maxjobsize, Set<Coefficients> coefficientses, Set<Printers> printersesForPrinterid, Set<Grouppquota> grouppquotas, Set<Printers> printersesForGroupid, Set<Userpquota> userpquotas) {
       this.printername = printername;
       this.description = description;
       this.priceperpage = priceperpage;
       this.priceperjob = priceperjob;
       this.passthrough = passthrough;
       this.maxjobsize = maxjobsize;
       this.coefficientses = coefficientses;
       this.printersesForPrinterid = printersesForPrinterid;
       this.grouppquotas = grouppquotas;
       this.printersesForGroupid = printersesForGroupid;
       this.userpquotas = userpquotas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="printername", unique=true, nullable=false)
    public String getPrintername() {
        return this.printername;
    }
    
    public void setPrintername(String printername) {
        this.printername = printername;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="priceperpage", precision=12, scale=0)
    public Float getPriceperpage() {
        return this.priceperpage;
    }
    
    public void setPriceperpage(Float priceperpage) {
        this.priceperpage = priceperpage;
    }

    
    @Column(name="priceperjob", precision=12, scale=0)
    public Float getPriceperjob() {
        return this.priceperjob;
    }
    
    public void setPriceperjob(Float priceperjob) {
        this.priceperjob = priceperjob;
    }

    
    @Column(name="passthrough", length=2)
    public String getPassthrough() {
        return this.passthrough;
    }
    
    public void setPassthrough(String passthrough) {
        this.passthrough = passthrough;
    }

    
    @Column(name="maxjobsize")
    public Integer getMaxjobsize() {
        return this.maxjobsize;
    }
    
    public void setMaxjobsize(Integer maxjobsize) {
        this.maxjobsize = maxjobsize;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="printers")
    public Set<Coefficients> getCoefficientses() {
        return this.coefficientses;
    }
    
    public void setCoefficientses(Set<Coefficients> coefficientses) {
        this.coefficientses = coefficientses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="printergroupsmembers", catalog="pykota", joinColumns = { 
        @JoinColumn(name="groupid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="printerid", nullable=false, updatable=false) })
    public Set<Printers> getPrintersesForPrinterid() {
        return this.printersesForPrinterid;
    }
    
    public void setPrintersesForPrinterid(Set<Printers> printersesForPrinterid) {
        this.printersesForPrinterid = printersesForPrinterid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="printers")
    public Set<Grouppquota> getGrouppquotas() {
        return this.grouppquotas;
    }
    
    public void setGrouppquotas(Set<Grouppquota> grouppquotas) {
        this.grouppquotas = grouppquotas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="printergroupsmembers", catalog="pykota", joinColumns = { 
        @JoinColumn(name="printerid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="groupid", nullable=false, updatable=false) })
    public Set<Printers> getPrintersesForGroupid() {
        return this.printersesForGroupid;
    }
    
    public void setPrintersesForGroupid(Set<Printers> printersesForGroupid) {
        this.printersesForGroupid = printersesForGroupid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="printers")
    public Set<Userpquota> getUserpquotas() {
        return this.userpquotas;
    }
    
    public void setUserpquotas(Set<Userpquota> userpquotas) {
        this.userpquotas = userpquotas;
    }




}


